# ===== NekoPlayer 的 mpv 配置（跨平台）=====

# 用 uosc 现代 UI 替代默认控制条（需安装 uosc 脚本，见项目说明）
osc=no
osd-bar=no
border=no

# 硬件解码
hwdec=auto

# 字幕 / 音轨 默认中文优先
slang=chi,zh,chs,sc,zho,cht
alang=chi,zh,zho,jpn,eng
sub-auto=fuzzy

# 播放结束自动关窗
keep-open=no
